version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    expose:
      - 8080
    environment:
      NODE_ENV: development
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/app/backend/src
      - /app/backend/node_modules
    command: npm run start:dev
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    expose:
      - 3000
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    command: npm run start:dev